Controllers/HoiDongController.cs
using PagedList;
using QLDoAn.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDoAn.Controllers
{
    public class HoiDongController : Controller
    {
        // GET: HoiDong
        private QuanLyDoAnEntities db = new QuanLyDoAnEntities();
        public ActionResult Index(int page = 1, int pageSize = 5)
        {
            var model = db.Tbl_HDCham.OrderBy(x => x.ID).ToPagedList(page, pageSize);
            return View(model);
        }


        //Xóa 
        public JsonResult Delete(long ID)
        {

            try
            {
                var hdc = db.Tbl_HDCham.Find(ID);
                foreach(var item in db.Tbl_HoiDong.Where(x => x.HDCham_ID == hdc.ID))
                {
                    db.Tbl_HoiDong.Remove(item);
                }
                db.Tbl_HDCham.Remove(hdc);
                db.SaveChanges();
                return Json(new
                {
                    status = true
                });
            }
            catch
            {
                return Json(new
                {
                    status = false
                });
            }

        }

        public ActionResult Add()
        {
            ViewBag.Khoa = db.Tbl_Khoa.ToList();
            return View();
        }


        [HttpPost]
        public ActionResult addHoiDong(Tbl_HDCham entity)
        {

            db.Tbl_HDCham.Add(entity);
            db.SaveChanges();
            var gv = Session["add_gv"] as List<Tbl_GiaoVien>;
            foreach(var item in gv)
            {
                var hd = new Tbl_HoiDong();
                hd.GiaoVien_ID = item.ID;
                hd.HDCham_ID = db.Tbl_HDCham.Max(x => x.ID);
                db.Tbl_HoiDong.Add(hd);
                db.SaveChanges();
            }
            Session["add_gv"] = null;
            TempData["add_success"] = "Thêm hội đồng chấm thành công";
            return RedirectToAction("Index");

        }


        public JsonResult addGV(long ID)
        {
            var cart = Session["add_gv"];
            if (cart != null)//Nếu giỏ đã chứa
            {
                var list = (List<Tbl_GiaoVien>)cart;
                if (!list.Exists(x => x.ID == ID))
                {
                    //Tạo đối tượng mới
                    var item = db.Tbl_GiaoVien.Find(ID);
                    list.Add(item);
                }
                else
                {
                    return Json(new
                    {
                        status = false
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            else//nếu giỏ hàng trống
            {
                var item = db.Tbl_GiaoVien.Find(ID);
                var list = new List<Tbl_GiaoVien>();
                list.Add(item);

                Session["add_gv"] = list;
            }
            return Json(new
            {
                status = true
            }, JsonRequestBehavior.AllowGet);

        }

        public JsonResult Delete_GV(long ID)
        {
            var cartSec = (List<Tbl_GiaoVien>)Session["add_gv"];
            cartSec.RemoveAll(x => x.ID == ID);
            Session["add_gv"] = cartSec;
            return Json(new
            {
                status = true
            });
        }

        //Xóa giáo viên trong hội đồng khi sửa
        public JsonResult DeleteHD(long ID)
        {

            try
            {
                var hd = db.Tbl_HoiDong.Find(ID);
                db.Tbl_HoiDong.Remove(hd);
                db.SaveChanges();
                return Json(new
                {
                    status = true
                });
            }
            catch
            {
                return Json(new
                {
                    status = false
                });
            }

        }

        //Thêm giáo viên vào hội đồng khi sửa
        public JsonResult Add_GVHD(long GiaoVien_ID, long HDCham_ID)
        {

            try
            {
                var hd = new Tbl_HoiDong();
                hd.GiaoVien_ID = GiaoVien_ID;
                hd.HDCham_ID = HDCham_ID;
                db.Tbl_HoiDong.Add(hd);
                db.SaveChanges();
                return Json(new
                {
                    status = true
                });
            }
            catch
            {
                return Json(new
                {
                    status = false
                });
            }

        }

        public ActionResult Edit(long ID)
        {
            ViewBag.HDC = db.Tbl_HDCham.Find(ID);
            ViewBag.Khoa = db.Tbl_Khoa.ToList();
            ViewBag.HD = db.Tbl_HoiDong.Where(x => x.HDCham_ID == ID).ToList();
            return View();
        }

        [HttpPost]
        public ActionResult editHoiDong(Tbl_HDCham entity)
        {
            var prv = db.Tbl_HDCham.Find(entity.ID);
            prv.TenHoiDong = entity.TenHoiDong;
            db.SaveChanges();
            
            TempData["add_success"] = "Sửa hội đồng chấm thành công";
            return RedirectToAction("Index");
        }

        public JsonResult GethdByID(long ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var hd = db.Tbl_HoiDong.Find(ID);
            return Json(hd, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/HoiDong/Add.cshtml
@using QLDoAn.Models.EF;
@{
    ViewBag.Title = "Thêm hội đồng";
    ViewBag.Navbar = "Quản lý hội đồng";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var lstKhoa = ViewBag.Khoa as List<Tbl_Khoa>;
    var session_gv = Session["add_gv"] as List<Tbl_GiaoVien>;
    int dem = 1;
}

<div class="content">
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-icon" data-background-color="blue">
                        <i class="material-icons">add_circle_outline</i>
                    </div>
                    <div class="card-content">
                        <h4 class="card-title">
                            Thêm giáo viên trong hội đồng
                        </h4>
                        <!-- Normal Information -->
                        
                        <div class="row">
                            <div class="col-md-2 dropdown-label">
                                <p>Thuộc khoa:</p>
                            </div>
                            <div class="col-md-3">
                                <select class="form-control" name="Khoa_ID" data-style="btn btn-primary btn-round" required
                                        title="Chọn khoa">
                                    <option value="" disabled selected>Chọn khoa</option>
                                    @foreach (var item in lstKhoa)
                                    {
                                        <option value="@item.ID">@item.TenKhoa</option>
                                    }
                                </select>
                            </div>
                            <div class="col-md-2 dropdown-label">
                                <p>Thuộc ngành:</p>
                            </div>
                            <div class="col-md-3">
                                <select class="form-control" name="ChuyenNganh_ID" data-style="btn btn-primary btn-round" required
                                        title="Chọn ngành">
                                    <option value="" disabled selected>Chọn ngành</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 dropdown-label">
                                <p>Chọn giáo viên:</p>
                            </div>
                            <div class="col-md-3">
                                <select class="form-control" name="GiaoVien_ID" data-style="btn btn-primary btn-round" required
                                        title="Chọn giáo viên">
                                    <option value="" disabled selected>Chọn giáo viên</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <button type="button" id="add_GV" class="btn btn-success btn-fill">Thêm giáo viên</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- end col-md-12 -->
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-icon" data-background-color="blue">
                        <i class="material-icons">list_alt</i>
                    </div>
                    <div class="card-content">
                        <h4 class="card-title">Danh sách giáo viên trong hội đồng</h4>
                        <div class="toolbar">
                            <!--        Here you can write extra buttons/actions for the toolbar              -->
                        </div>
                        <div class="material-datatables">

                            <table id="datatables2"
                                   class="table table-striped display responsive table-no-bordered table-hover nowrap"
                                   style="width:100%">
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>Họ tên giáo viên</th>
                                        <th class="disabled-sorting"></th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @if (session_gv != null)
                                    {
                                        
                                        foreach (var item in session_gv)
                                        {
                                            <tr>
                                                <td>@dem</td>
                                                <td>@item.TenGiaoVien</td>
                                                <td class="td-actions">
                                                    <button type="button" rel="tooltip"
                                                            class="btn btn-danger btn-round btnDelete" data-id="@item.ID" title="Xóa giáo viên">
                                                        <!-- Link on demo.js: warning-message-and-confirmation-6 -->
                                                        <i class="material-icons">close</i>
                                                    </button>
                                                </td>
                                            </tr>
                                            dem++;
                                        }
                                    }
                                </tbody>
                            </table>

                        </div>
                    </div>
                    <!-- end content-->
                </div>
                <!--  end card  -->
            </div>
            <!-- end col-md-12 -->
        </div>
        <div class="row">

            <div class="col-md-12">
                <div class="card">
                    <div class="card-content">
                        @using (Html.BeginForm("addHoiDong", "HoiDong", FormMethod.Post, new { id = "frmAdd" }))
                        {
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Tên hội đồng *</label>
                                        <input type="text" name="TenHoiDong" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="pull-right">
                                <button type="submit" class="btn btn-success btn-fill">Tạo hội đồng chấm</button>
                                <div class="clearfix"></div>
                            </div>
                        }
                    </div>
                </div>

            </div>
            <!-- end col-md-12 -->
        </div>

    </div>

</div>

@section jsScript{

    <script>
        $(document).ready(function () {
            $('select[name="Khoa_ID"]').change(function () {
                var ID = this.value;
                $.ajax({
                    url: '/DoAn/GetChuyenNganhByKhoa/' + ID,
                    type: 'get',
                    dataType: 'json',
                    contentType: "application/json;charset=utf-8",
                    success: function (response) {
                        $('select[name="ChuyenNganh_ID"]').empty();
                        var def = "<option disabled selected>Chọn chuyên ngành</option>";
                        $('select[name="ChuyenNganh_ID"]').append(def);
                        $.each(response, function (i, item) {
                            var option = "<option value='" + response[i].ID + "'>" + response[i].ChuyenNganh + "</option>";

                            $('select[name="ChuyenNganh_ID"]').append(option);
                        });
                        console.log(response)

                    }
                });
            });

            $('select[name="ChuyenNganh_ID"]').change(function () {
                var ID = this.value;
                $.ajax({
                    url: '/DoAn/GetGVByChuyenNganh/' + ID,
                    type: 'get',
                    dataType: 'json',
                    contentType: "application/json;charset=utf-8",
                    success: function (response) {
                        $('select[name="GiaoVien_ID"]').empty();
                        var def = "<option disabled selected>Chọn giáo viên</option>";
                        $('select[name="GiaoVien_ID"]').append(def);
                        $.each(response, function (i, item) {
                            var option = "<option value='" + response[i].ID + "'>" + response[i].TenGiaoVien + "</option>";

                            $('select[name="GiaoVien_ID"]').append(option);
                        });

                    }
                });
            });

            $("#add_GV").click(function () {
                var ID = $('select[name="GiaoVien_ID"]').val();
                $.ajax({
                    url: '/HoiDong/addGV',
                    data: {
                        ID: ID
                    },
                    dataType: 'Json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/HoiDong/Add";
                            PNotify.success({
                                title: 'THÔNG BÁO!!',
                                text: 'Thêm giáo viên thành công.'
                            });
                        } else {
                            PNotify.error({
                                title: 'THÔNG BÁO!!',
                                text: 'Thêm giáo viên KHÔNG thành công hoặc giáo viên đã được thêm vào hội đồng.'
                            });
                        }
                    }
                });
            });

            $('.btnDelete').off('click').on('click', function () {

                $.ajax({
                    data: { ID: $(this).data('id') },
                    url: '/HoiDong/Delete_GV',
                    dataType: 'Json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/HoiDong/Add";
                            PNotify.success({
                                title: 'THÔNG BÁO!!',
                                text: 'Xóa giáo viên thành công.'
                            });
                        } else {
                            PNotify.error({
                                title: 'THÔNG BÁO!!',
                                text: 'Xóa giáo viên KHÔNG thành công.'
                            });
                        }
                    }
                });
            });
        });
    </script>

}

Views/HoiDong/Edit.cshtml
@using QLDoAn.Models.EF;
@{
    ViewBag.Title = "Sửa hội đồng";
    ViewBag.Navbar = "Quản lý hội đồng";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var lstKhoa = ViewBag.Khoa as List<Tbl_Khoa>;
    var lstHD = ViewBag.HD as List<Tbl_HoiDong>;
    var hdc = ViewBag.HDC as Tbl_HDCham;
    int dem = 1;
}

<div class="content">
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-icon" data-background-color="blue">
                        <i class="material-icons">add_circle_outline</i>
                    </div>
                    <div class="card-content">
                        <h4 class="card-title">
                            Thêm giáo viên trong hội đồng
                        </h4>
                        <!-- Normal Information -->

                        <div class="row">
                            <div class="col-md-2 dropdown-label">
                                <p>Thuộc khoa:</p>
                            </div>
                            <div class="col-md-3">
                                <select class="form-control" name="Khoa_ID" data-style="btn btn-primary btn-round" required
                                        title="Chọn khoa">
                                    <option value="" disabled selected>Chọn khoa</option>
                                    @foreach (var item in lstKhoa)
                                    {
                                        <option value="@item.ID">@item.TenKhoa</option>
                                    }
                                </select>
                            </div>
                            <div class="col-md-2 dropdown-label">
                                <p>Thuộc ngành:</p>
                            </div>
                            <div class="col-md-3">
                                <select class="form-control" name="ChuyenNganh_ID" data-style="btn btn-primary btn-round" required
                                        title="Chọn ngành">
                                    <option value="" disabled selected>Chọn ngành</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 dropdown-label">
                                <p>Chọn giáo viên:</p>
                            </div>
                            <div class="col-md-3">
                                <select class="form-control" name="GiaoVien_ID" data-style="btn btn-primary btn-round" required
                                        title="Chọn giáo viên">
                                    <option value="" disabled selected>Chọn giáo viên</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <button type="button" id="add_GV" class="btn btn-default btn-fill">Thêm giáo viên</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- end col-md-12 -->
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-icon" data-background-color="blue">
                        <i class="material-icons">list_alt</i>
                    </div>
                    <div class="card-content">
                        <h4 class="card-title">Danh sách giáo viên trong hội đồng: <span>@hdc.TenHoiDong</span></h4>
                        <div class="toolbar">
                            <!--        Here you can write extra buttons/actions for the toolbar              -->
                        </div>
                        <div class="material-datatables">

                            <table id="datatables2"
                                   class="table table-striped display responsive table-no-bordered table-hover nowrap"
                                   style="width:100%">
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>Họ tên giáo viên</th>
                                        <th class="disabled-sorting"></th>
                                    </tr>
                                </thead>

                                <tbody>
                                    
                                        @foreach (var item in lstHD)
                                        {
                                            <tr>
                                                <td>@dem</td>
                                                <td>@item.Tbl_GiaoVien.TenGiaoVien</td>
                                                <td class="td-actions">
                                                    <button type="button" rel="tooltip"
                                                            class="btn btn-danger btn-round btnDelete" data-id="@item.ID" title="Xóa giáo viên">
                                                        <!-- Link on demo.js: warning-message-and-confirmation-6 -->
                                                        <i class="material-icons">close</i>
                                                    </button>
                                                </td>
                                            </tr>
                                            dem++;
                                        }
                                </tbody>
                            </table>

                        </div>
                    </div>
                    <!-- end content-->
                </div>
                <!--  end card  -->
            </div>
            <!-- end col-md-12 -->
        </div>
        <div class="row">

            <div class="col-md-12">
                <div class="card">
                    <div class="card-content">
                        @using (Html.BeginForm("editHoiDong", "HoiDong", FormMethod.Post, new { id = "frmAdd" }))
                        {
                            <input type="hidden" name="ID" value="@hdc.ID"/>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Tên hội đồng *</label>
                                        <input type="text" name="TenHoiDong" class="form-control" required value="@hdc.TenHoiDong">
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="pull-right">
                                <button type="submit" class="btn btn-success btn-fill">Sửa hội đồng chấm</button>
                                <div class="clearfix"></div>
                            </div>
                        }
                    </div>
                </div>

            </div>
            <!-- end col-md-12 -->
        </div>

    </div>

</div>

@section jsScript{

    <script>
        $(document).ready(function () {
            $('select[name="Khoa_ID"]').change(function () {
                var ID = this.value;
                $.ajax({
                    url: '/DoAn/GetChuyenNganhByKhoa/' + ID,
                    type: 'get',
                    dataType: 'json',
                    contentType: "application/json;charset=utf-8",
                    success: function (response) {
                        $('select[name="ChuyenNganh_ID"]').empty();
                        var def = "<option disabled selected>Chọn chuyên ngành</option>";
                        $('select[name="ChuyenNganh_ID"]').append(def);
                        $.each(response, function (i, item) {
                            var option = "<option value='" + response[i].ID + "'>" + response[i].ChuyenNganh + "</option>";

                            $('select[name="ChuyenNganh_ID"]').append(option);
                        });
                        console.log(response)

                    }
                });
            });

            $('select[name="ChuyenNganh_ID"]').change(function () {
                var ID = this.value;
                $.ajax({
                    url: '/DoAn/GetGVByChuyenNganh/' + ID,
                    type: 'get',
                    dataType: 'json',
                    contentType: "application/json;charset=utf-8",
                    success: function (response) {
                        $('select[name="GiaoVien_ID"]').empty();
                        var def = "<option disabled selected>Chọn giáo viên</option>";
                        $('select[name="GiaoVien_ID"]').append(def);
                        $.each(response, function (i, item) {
                            var option = "<option value='" + response[i].ID + "'>" + response[i].TenGiaoVien + "</option>";

                            $('select[name="GiaoVien_ID"]').append(option);
                        });

                    }
                });
            });

            $("#add_GV").click(function () {
                var ID = $('select[name="GiaoVien_ID"]').val();
                var hdcham = @hdc.ID;
                $.ajax({
                    url: '/HoiDong/Add_GVHD',
                    data: {
                        GiaoVien_ID: ID,
                        HDCham_ID: hdcham
                    },
                    dataType: 'Json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/HoiDong/Edit/@hdc.ID";
                            PNotify.success({
                                title: 'THÔNG BÁO!!',
                                text: 'Thêm giáo viên thành công.'
                            });
                        } else {
                            PNotify.error({
                                title: 'THÔNG BÁO!!',
                                text: 'Thêm giáo viên KHÔNG thành công hoặc giáo viên đã được thêm vào hội đồng.'
                            });
                        }
                    }
                });
            });

            $('.btnDelete').off('click').on('click', function () {

                $.ajax({
                    data: { ID: $(this).data('id') },
                    url: '/HoiDong/DeleteHD',
                    dataType: 'Json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/HoiDong/Edit/@hdc.ID";
                            PNotify.success({
                                title: 'THÔNG BÁO!!',
                                text: 'Xóa giáo viên thành công.'
                            });
                        } else {
                            PNotify.error({
                                title: 'THÔNG BÁO!!',
                                text: 'Xóa giáo viên KHÔNG thành công.'
                            });
                        }
                    }
                });
            });
        });
    </script>

}